#!/bin/bash
clear
echo ' '
echo ' '
echo ' '
echo ' '
echo ' '
echo ' '
echo ' '
cat << EOF
BBBBBBBBBBBBBBBBB                                         kkkkkkkk           HHHHHHHHH     HHHHHHHHH                                      kkkkkkkk
B::::::::::::::::B                                        k::::::k           H:::::::H     H:::::::H                                      k::::::k
B::::::BBBBBB:::::B                                       k::::::k           H:::::::H     H:::::::H                                      k::::::k
BB:::::B     B:::::B                                      k::::::k           HH::::::H     H::::::HH                                      k::::::k
  B::::B     B:::::B  aaaaaaaaaaaaa       cccccccccccccccc k:::::k    kkkkkkk  H:::::H     H:::::H    aaaaaaaaaaaaa       cccccccccccccccc k:::::k    kkkkkkk
  B::::B     B:::::B  a::::::::::::a    cc:::::::::::::::c k:::::k   k:::::k   H:::::H     H:::::H    a::::::::::::a    cc:::::::::::::::c k:::::k   k:::::k
  B::::BBBBBB:::::B   aaaaaaaaa:::::a  c:::::::::::::::::c k:::::k  k:::::k    H::::::HHHHH::::::H    aaaaaaaaa:::::a  c:::::::::::::::::c k:::::k  k:::::k
  B:::::::::::::BB             a::::a c:::::::cccccc:::::c k:::::k k:::::k     H:::::::::::::::::H             a::::a c:::::::cccccc:::::c k:::::k k:::::k
  B::::BBBBBB:::::B     aaaaaaa:::::a c::::::c     ccccccc k::::::k:::::k      H:::::::::::::::::H      aaaaaaa:::::a c::::::c     ccccccc k::::::k:::::k
  B::::B     B:::::B  aa::::::::::::a c:::::c              k:::::::::::k       H::::::HHHHH::::::H    aa::::::::::::a c:::::c              k:::::::::::k
  B::::B     B:::::B a::::aaaa::::::a c:::::c              k:::::::::::k       H:::::H     H:::::H   a::::aaaa::::::a c:::::c              k:::::::::::k
  B::::B     B:::::Ba::::a    a:::::a c::::::c     ccccccc k::::::k:::::k      H:::::H     H:::::H  a::::a    a:::::a c::::::c     ccccccc k::::::k:::::k
BB:::::BBBBBB::::::Ba::::a    a:::::a c:::::::cccccc:::::ck::::::k k:::::k   HH::::::H     H::::::HHa::::a    a:::::a c:::::::cccccc:::::ck::::::k k:::::k
B:::::::::::::::::B a:::::aaaa::::::a  c:::::::::::::::::ck::::::k  k:::::k  H:::::::H     H:::::::Ha:::::aaaa::::::a  c:::::::::::::::::ck::::::k  k:::::k
B::::::::::::::::B   a::::::::::aa:::a  cc:::::::::::::::ck::::::k   k:::::k H:::::::H     H:::::::H a::::::::::aa:::a  cc:::::::::::::::ck::::::k   k:::::k
BBBBBBBBBBBBBBBBB     aaaaaaaaaa  aaaa    cccccccccccccccckkkkkkkk    kkkkkkkHHHHHHHHH     HHHHHHHHH  aaaaaaaaaa  aaaa    cccccccccccccccckkkkkkkk    kkkkkkk
EOF
echo ' '
echo ' '
echo ' '
echo "These IPs will be scanned"
echo ' '
        #sudo ssh starfury000@192.168.1.9
        #sudo grep "Ban" /var/log/fail2ban.log | cut -d ' ' -f16- | tee ~/Documents/Scans/BackHack/"IPlist-$(da$
#verify list to scan
cat ~/Documents/Scans/starrnet.txt
echo ' '
echo ' '
read -p "Press [Enter] key to start BackHack..."
echo "BackHack is Running!"
echo ' '
echo ' '
#run namp of IPlist on pentest host
#nmap -sS -sU -T4 -A -v -PE -PP -PS80,443 -PA3389 -PU40125 -PY -g 53 --script "default or (discovery and safe)" ~/Documents/Scans/IPLlist.txt | tee ~/Documents/Scans/BackHack/"IPlist-$(date +%s).txt"
